// <auto-generated />
namespace SoporteEnLinea.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eliminandoroleiddesql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eliminandoroleiddesql));
        
        string IMigrationMetadata.Id
        {
            get { return "201805161404086_eliminando-roleid-de-sql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
